### ISSUE TITLE
Trying bundled dependencies fails due to missing true.mustache

### ISSUE THREAD

**Issue by Frank-Steiner** [theforeman/npm2rpm#71]
Hi,
just tried npm2rpm for the first time so just followed the example in the readme, and `./bin/npm2rpm.js -n webpack -v 4.20.2` works find.

However, using it with -s failed:
```
euler [15:47] soft 5077) node_modules/.bin/npm2rpm -s -n webpack -v 4.20.2
---- npm2rpm ----
-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
 - Undefined output directory - defaulting to npm2rpm
 - Starting npm module download: https://registry.npmjs.org/webpack/-/webpack-4.20.2.tgz
 - Unpacking in /tmp/npm2rpm-263084ihZJZo1XIEn ...
 - Finished extracting for webpack
 - Reading package.json for webpack
Warning: No README data
 - Finished reading package.json for webpack
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/local/soft/node_modules/npm2rpm/true.mustache'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at generateSpecFile (/local/soft/node_modules/npm2rpm/lib/spec_file_generator.js:186:24)
    at writeSpecFile (/local/soft/node_modules/npm2rpm/bin/npm2rpm.js:106:19)
    at Unpack.<anonymous> (/local/soft/node_modules/npm2rpm/bin/npm2rpm.js:101:5)
    at Unpack.emit (node:events:513:28)
    at Unpack.[maybeClose] (/local/soft/node_modules/tar/lib/unpack.js:215:12)
    at Unpack.[unpend] (/local/soft/node_modules/tar/lib/unpack.js:493:21)
    at /local/soft/node_modules/tar/lib/unpack.js:401:55
    at FSReqCallback.oncomplete (node:fs:192:23) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/local/soft/node_modules/npm2rpm/true.mustache'
}
```

Am I doing sth. wrong...?
cu,
Frank

**Comment by evgeni** [comment]
It needs to be `-s <strategy_name>`, so either `-s single` or `-s bundle`

**Comment by Frank-Steiner** [comment]
Oh, I really feel stupid having missed that. Sorry! And thanks a lot, it works now!
